### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by rsanting** [eliashaeussler/cache-warmup-action#18]
### PHP version

8.3

### Action version

1.0.0

### Operating system

ubuntu-latest

### Current behavior

When running the action it exits with exit code 2

It seems to be caused by the fetching of the secret key in main.sh

gpg --keyserver keys.openpgp.org --recv-keys E73F20790A629A2CEF2E9AE57C1C5363490E851E
gpg: key 7C1C5363490E851E: no user ID
gpg: Total number processed: 1

If we run the exit code of just the gpg command we get 2

echo $?
2

### Expected behavior

The action doesn't exit with exit code 2

**Comment by eliashaeussler** [comment]
Hi @rsanting, thanks for your bug report. It seems like I accidentally removed the user identities from the GPG key. This is now fixed and everything should work as expected.
